version: '3'
services:
  node:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: login_api
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    depends_on:
      - "database"
    environment:
      MYSQL_HOST: database
      MYSQL_PORT: 3306
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    env_file:
      - .env

  database:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_USER_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
    ports:
      - ${MYSQL_PORT}:3306